name: C/C++ CI

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: cd lib_jtag_core/build/linux && make

  build-windows-x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: sudo apt install -q -y mingw-w64 && cd build && make TARGET=mingw32
    - name: Package
      run: cd build && ./windowscreatezip.sh _x86
    - uses: actions/upload-artifact@main
      with:
        name: jtag-boundary-scanner-winx86-${{ github.sha }}
        path: build/JTAGBoundaryScanner_win_x86.zip
